# Generated by Django 4.0.3 on 2022-03-24 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_task_user_alter_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_finished',
            field=models.DateTimeField(default=0),
        ),
    ]
